config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'vacancies#index'

  resources :vacancies do
    get :candidates, on: :member
  end

  resources :candidates do
    get :vacancies, on: :member
  end

  resources :skills, only: [] do
    get :search, on: :collection
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/candidate.rb
class Candidate < ApplicationRecord
  include Contactable
  acts_as_taggable_on :skills
  enum status: [ :active_search, :employed ]

  ThinkingSphinx::Callbacks.append(self, :tag, :behaviours => [:real_time], :path => [:skills])
    
  validates :desired_salary, :name, :middle_name, :surname, :skill_list, :status, presence: true
  validates :name, :middle_name, :surname, format: { with: /[а-я]+/i,
                                                     message: "only cyrillic letters without spaces" }

  def full_name
    "#{surname} #{name} #{middle_name}"
  end
end

app/models/concerns/contactable.rb
module Contactable
  extend ActiveSupport::Concern

  included do
    validates :phone_number, format: { with: /\A(\d{3})\D*(\d{3})\D*(\d{2})\D*(\d{2})\z/, 
                                        message: "wrong format", allow_blank: true }
    validates :email, format: { with: /\A[a-zA-Z0-9.!#$%&'*+\/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*\z/, 
                                  message: "wrong format", allow_blank: true }
                                  
    validates :phone_number, presence: true, if: -> { email.blank? }
    validates :email,        presence: true, if: -> { phone_number.blank? }

    def contact_number
      n = phone_number
      "+7 (#{n[0..2]}) #{n[3..5]}-#{n[6..7]}-#{n[8..9]}" unless n.blank?
    end
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
end

app/models/vacancy.rb
class Vacancy < ApplicationRecord
  include Contactable
  acts_as_taggable_on :skills  
  
  ThinkingSphinx::Callbacks.append(self, :tag, :behaviours => [:real_time], :path => [:skills])

  validates :title, :expiration_date, :salary, :skill_list, presence: true

  default_scope { order(salary: :desc) }
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
  before_action :find_candidate, only: %i[show edit update destroy vacancies]

  def index
    respond_with @candidates = Candidate.all
  end

  def show
    respond_with @candidate
  end

  def new
  end

  def create
    respond_with(@candidate = Candidate.create(candidate_params))
  end

  def edit
  end

  def update
    @candidate.update(candidate_params)
    respond_with(@candidate)
  end

  def destroy
    respond_with(@candidate.destroy)
  end

  def vacancies
    full_match = Vacancy.tagged_with(@candidate.skill_list, :match_all => true)
    partial_match = Vacancy.tagged_with(@candidate.skill_list, :any => true) - full_match
    
    @vacancies = { full_match: full_match, partial_match: partial_match }
  end

  private

  def find_candidate
    @candidate = Candidate.find(params[:id])
  end

  def candidate_params
    params.require(:candidate).permit(:name, :middle_name, :surname, :desired_salary, :phone_number, :email, :skill_list)
  end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  
  def search
    @result = params[:name].empty? ? [] : Tag.search(params[:name])

    respond_to do |format|
      format.json { render json: @result }
    end
  end
end

app/controllers/vacancies_controller.rb
class VacanciesController < ApplicationController
  before_action :find_vacancy, only: %i[show edit update destroy candidates]

  def index
    respond_with @vacancies = Vacancy.all
  end

  def show
    respond_with @vacancy
  end

  def new
  end

  def create
    respond_with(@vacancy = Vacancy.create(vacancy_params))
  end

  def edit
  end

  def update
    @vacancy.update(vacancy_params)
    respond_with(@vacancy)
  end

  def destroy
    respond_with(@vacancy.destroy)
  end

  def candidates
    full_match = Candidate.tagged_with(@vacancy.skill_list, :match_all => true)
    partial_match = Candidate.tagged_with(@vacancy.skill_list, :any => true) - full_match
    
    @candidates = { full_match: full_match, partial_match: partial_match }
  end

  private

  def find_vacancy
    @vacancy = Vacancy.find(params[:id])
  end

  def vacancy_params
    params.require(:vacancy).permit(:title, :salary, :phone_number, :email, :expiration_date, :skill_list)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/candidates/_candidate.html.slim
tr.candidate
  td= link_to candidate.full_name, candidate_path(candidate)
  td= candidate.desired_salary
  td= candidate.contact_number
  td= candidate.email
  td
    .me-1 = link_to "Edit", edit_candidate_path(candidate)
    = link_to "Delete", candidate_path(candidate), method: :delete, data: {confirm: "Are you sure?"}

app/views/candidates/_candidates.html.slim
table.table.bordered.candidates
  thead
    tr
      td Full name
      td Desired salary
      td Phone number
      td Email
      td Actions
  tbody
    - candidates.each do |candidate|
      = render "candidates/candidate", candidate: candidate

app/views/candidates/_form.html.slim
  - if @candidate&.errors.present?
    = render "shared/errors", resource: @candidate

  = form_with model: candidate = @candidate || Candidate.new, 
                url: candidate.persisted? ? candidate_path(@candidate) : candidates_path, 
              local: true do |f|

    .form-row
      = f.label :surname
      = f.text_field :surname, value: candidate.surname

    .form-row
      = f.label :name
      = f.text_field :name, value: candidate.name

    .form-row
      = f.label :middle_name
      = f.text_field :middle_name, value: candidate.middle_name

    .form-row
      = f.label :desired_salary
      = f.number_field :desired_salary, value: candidate.desired_salary

    .form-row
      = f.label :phone_number
      = f.text_field :phone_number, value: candidate.phone_number

    .form-row
      = f.label :email
      = f.text_field :email, value: candidate.email

    h3 Skills
    ul#skills *{data: {klass: "candidate"}}
      - if candidate.skills.present?
        - candidate.skills.each do |skill|
          li = skill.name

    .form-row
      = text_field_tag :skill, nil, autocomplete: "off"
      = button_tag "Add skill", id: "add_skill", class: "btn btn-dark btn-sm ms-3"
      ul#search_results

    .form-row
      = f.submit

app/views/candidates/edit.html.slim
h2 Edit candidate
= render "candidates/form"

= link_to "Back to candidates", candidates_path

app/views/candidates/index.html.slim
h1 Candidates list

= link_to "Add candidate", new_candidate_path
br
br

-if @candidates.present?
  = render partial: "candidates", locals: { candidates: @candidates }
-else
  p No candidates yet

app/views/candidates/new.html.slim
h2 New candidate
= render "candidates/form"

= link_to "Back to candidates", candidates_path

app/views/candidates/show.html.slim
h1= @candidate.full_name

strong Desired_salary: 
= @candidate.desired_salary
br
strong Phone number: 
= @candidate.contact_number
br
strong Email: 
= @candidate.email
br
br
strong Skills: 
= @candidate.skill_list.join(", ")
br
br

.mt-2 = link_to "Matching vacancies", vacancies_candidate_path(@candidate)
p.mt-2 
  = link_to "Edit", edit_candidate_path(@candidate)
  = link_to "Delete", candidate_path(@candidate), method: :delete, data: {confirm: "Are you sure?"}
.mt-3 = link_to "Back to candidates", candidates_path

app/views/candidates/vacancies.html.slim
h2 Full-match
- if @vacancies[:full_match].present?
  = render partial: "vacancies/vacancies", locals: { vacancies: @vacancies[:full_match] }
- else
  No vacancies.

h2 Partial-match
- if @vacancies[:partial_match].present?
  = render partial: "vacancies/vacancies", locals: { vacancies: @vacancies[:partial_match] }
- else
  No vacancies.

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StaffAgency</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.slim
<!DOCTYPE html>
html
  head
    title StaffAgency
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'

  body
    = render 'shared/flash'
    = render 'shared/nav'

    .container 
      = yield

app/views/layouts/sample_application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StaffAgency</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_errors.html.slim
= content_tag :div, class: "errors"
  h2 = "Error".pluralize(resource.errors.count) + " ocurred:"
  ul
    - resource.errors.full_messages.each do |mes|
      li = mes

app/views/shared/_flash.html.slim
- if flash[:notice].present?
  .alert.alert-primary
    p.notice = notice

- if flash[:alert].present?
  .alert.alert-primary
    p.alert = alert

app/views/shared/_nav.html.slim
.navbar-nav.navbar.navbar-collapse
  ul.breadcrumb
    li.breadcrumb-item = link_to "Vacancies", vacancies_path
    li.breadcrumb-item = link_to "Candidates", candidates_path

app/views/vacancies/_form.html.slim
  - if @vacancy&.errors.present?
    = render "shared/errors", resource: @vacancy

  = form_with model: vacancy = @vacancy || Vacancy.new, 
                url: vacancy.persisted? ? vacancy_path(@vacancy) : vacancies_path,
              local: true do |f|

    .form-row
      = f.label :title
      = f.text_field :title, value: vacancy.title
    
    .form-row
      = f.label :salary
      = f.number_field :salary, value: vacancy.salary

    .form-row
      = f.label :phone_number
      = f.text_field :phone_number, value: vacancy.phone_number

    .form-row
      = f.label :email
      = f.text_field :email, value: vacancy.email

    .form-row
      = f.label :expiration_date
      = f.date_field :expiration_date, value: vacancy.expiration_date

    h3 Skills
    ul#skills *{data: {klass: "vacancy"}}
      - if vacancy.skills.present?
        - vacancy.skills.each do |skill|
          li = skill.name

    .form-row
      = text_field_tag :skill, nil, autocomplete: "off"
      = button_tag "Add skill", id: "add_skill", class: "btn btn-dark btn-sm ms-3"
      ul#search_results

    .form-row
      = f.submit

app/views/vacancies/_vacancies.html.slim
table.table.bordered.vacancies
  thead
    tr
      td Title
      td Salary
      td Phone number
      td Email
      td Created date
      td Expiration date
      td Actions
  tbody
    - vacancies.each do |vacancy|
      = render "vacancies/vacancy", vacancy: vacancy

app/views/vacancies/_vacancy.html.slim
tr.vacancy
  td= link_to vacancy.title, vacancy_path(vacancy)
  td= vacancy.salary
  td= vacancy.contact_number
  td= vacancy.email
  td= vacancy.created_at
  td= vacancy.expiration_date
  td
    .me-1 = link_to "Edit", edit_vacancy_path(vacancy)
    = link_to "Delete", vacancy_path(vacancy), method: :delete, data: {confirm: "Are you sure?"}

app/views/vacancies/candidates.html.slim
h2 Full-match
- if @candidates[:full_match].present?
  = render partial: "candidates/candidates", locals: { candidates: @candidates[:full_match] }
- else
  p No candidates.

h2 Partial-match
- if @candidates[:partial_match].present?
  = render partial: "candidates/candidates", locals: { candidates: @candidates[:partial_match] }
- else
  p No candidates.

app/views/vacancies/edit.html.slim
h2 Edit vacancy
= render "vacancies/form"

= link_to "Back to vacancies", vacancies_path

app/views/vacancies/index.html.slim
h1 Vacancies list

= link_to "Add vacancy", new_vacancy_path
br
br

-if @vacancies.present?
  = render partial: "vacancies", locals: { vacancies: @vacancies }
-else
  p No vacancies yet

app/views/vacancies/new.html.slim
h2 New vacancy
= render "vacancies/form"
br
br

= link_to "Back to vacancies", vacancies_path

app/views/vacancies/show.html.slim
h1= @vacancy.title

strong Salary: 
= @vacancy.salary
br
strong Phone number: 
= @vacancy.contact_number
br
strong Email: 
= @vacancy.email
br
strong Created at: 
= @vacancy.created_at
br
strong Expiration date: 
= @vacancy.expiration_date
br
br
strong Skills: 
= @vacancy.skill_list.join(", ")
br
br

.mt-2 = link_to "Matching candidates", candidates_vacancy_path(@vacancy)
p.mt-2 
  = link_to 'Edit', edit_vacancy_path(@vacancy)
  = " / "
  = link_to "Delete", vacancy_path(@vacancy), method: :delete, data: {confirm: "Are you sure?"}
.mt-3 = link_to "Back to vacancies", vacancies_path